allowBuilds:
  "@avail-project/nexus-core": true
  "@reown/appkit": true
  bufferutil: true
  core-js: true
  esbuild: true
  keccak: true
  msgpackr-extract: true
  protobufjs: true
  secp256k1: true
  utf-8-validate: true
  "@avail-project/ca-common": true
  "@avail-project/nexus-types": true
  msw: true
  sharp: true
  unrs-resolver: true
  "@avail-project/nexus-core@https://codeload.github.com/availproject/nexus-sdk/tar.gz/98d56b2d2fcdd9291fd36fcba087ea0c3d61e399": true

blockExoticSubdeps: false

minimumReleaseAge: 5760
minimumReleaseAgeExclude:
  - "@avail-project/nexus-core"

overrides:
  "@protobufjs/utf8": "1.1.1"
  "@remix-run/router": "1.23.2"
  axios: "1.17.0"
  brace-expansion: "5.0.6"
  dompurify: "3.4.7"
  elliptic: "6.6.1"
  esbuild: "0.28.0"
  follow-redirects: "1.16.0"
  form-data: "4.0.6"
  hono: "4.12.23"
  postcss: "8.5.15"
  protobufjs: "8.5.0"
  qs: "6.15.2"
  uuid: "14.0.0"
  viem: "2.47.12"
  vite: "6.4.3"
  ws: "8.21.0"
